# Generated by Django 5.1.1 on 2024-12-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_planalimentacion_comidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteperfil',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10, null=True),
        ),
    ]
